version: "3.5"

services:
  app:
    volumes: &appvolumes
      # Host mounts with performance penalty, only put what is necessary here
      - ./www/app/code:/var/www/html/app/code:cached
      - ./www/app/design:/var/www/html/app/design:cached
      - ./www/app/etc:/var/www/html/app/etc:cached
      - ./www/composer.json:/var/www/html/composer.json:cached
      - ./www/composer.lock:/var/www/html/composer.lock:cached
      - ./www/nginx.conf.sample:/var/www/html/nginx.conf:cached
      - ./www/auth.json:/var/www/html/auth.json:cached
      #- ./www/m2-hotfixes:/var/www/html/m2-hotfixes:cached
      #- ./www/patches:/var/www/html/patches:cached
      #- ./www/var/log:/var/www/html/var/log:cached
      #- ./www/var/report:/var/www/html/var/report:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - ~/.ssh/known_hosts.old:/var/www/.ssh/known_hosts.old:cached



  phpfpm:
    volumes: *appvolumes
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  volumes: *appvolumes
