# Mark Shust's Docker Configuration for Magento
# (https://github.com/markshust/docker-magento)
#
# Version 33.0.0

version: "3"

services:
  app:
    volumes: &appvolumes
      # Host mounts with performance penalty, only put what is necessary here
      - ./www/app/code:/var/www/html/app/code:cached
      - ./www/app/design:/var/www/html/app/design:cached
      - ./www/app/etc:/var/www/html/app/etc:cached
      - ./www/composer.json:/var/www/html/composer.json:cached
      - ./www/composer.lock:/var/www/html/composer.lock:cached
      # - ./www/nginx.conf.sample:/var/www/html/nginx.conf:cached
      - ./www/auth.json:/var/www/html/auth.json:cached
      #- ./www/m2-hotfixes:/var/www/html/m2-hotfixes:cached
      #- ./www/patches:/var/www/html/patches:cached
      #- ./www/var/log:/var/www/html/var/log:cached
      #- ./www/var/report:/var/www/html/var/report:cached
      # To sync your SSH to the container, uncomment the following line:
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      # Linux only: remove the above lines and mount the entire src directory with:
      #- ./www:/var/www/html:cached

  phpfpm:
    volumes: *appvolumes
    # Linux only: host.docker.internal doesn't exist https://github.com/docker/for-linux/issues/264
    # Uncomment two lines below & replace IP with result of: docker run --rm alpine ip route | awk 'NR==1 {print $3}'
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

#  mailhog:
#    image: mailhog/mailhog
#    ports:
#      - "1025"
#      - "8025:8025"

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  volumes: *appvolumes
